import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer } from "@/modules/shared/components/footer";
import { Nav } from "@/modules/shared/components/nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-zinc-300 selection:bg-zinc-900 selection:text-zinc-300`}
      >
        <div className="px-4 w-full flex flex-col min-h-screen mx-auto max-w-6xl items-center justify-between font-sans">
          <Nav />
          {children}
          <Footer />
        </div> 
      </body>
    </html>
  );
}
