import type { Metadata } from "next";
import { getServerSideUser } from "@/modules/auth/actions/auth";
import { redirect } from "next/navigation";
import { Provider } from "@/modules/shared/components/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const user = await getServerSideUser()

  if(!user) {
    return redirect('/auth')
  }

  return (
    <>
      <Provider>
        {children}
      </Provider>
    </>
  );
}
